from selenium.webdriver.common.by import By

from_field = (By.ID, 'from')
to_field = (By.ID, 'to')
button_order_a_taxi = (By.XPATH, '//div[@class="type-picker shown"]/div[@class="results-container"]/div[@class="results-text"]/button')
comfort_rate = (By.XPATH, '//div[@class="tariff-cards"]/div[5]')
select_rate = comfort_rate
div_phone_number = (By.CLASS_NAME, 'np-text')
input_id_phone = (By.ID, 'phone')
next_phone_number = (By.XPATH, '(//div[@class="buttons"]/button)[1]')
confirm_code_phone_number = (By.XPATH, '(//div[@class="buttons"]/button)[2]')
input_text_code_phone_number = (By.ID, 'code')
close_modal_phone_number = (By.CLASS_NAME, 'close-button.section-close')
div_method_of_payment = (By.CLASS_NAME, 'pp-text')
add_a_card = (By.CLASS_NAME, 'pp-row.disabled')
card_input = (By.ID, 'number')
card_code_input = (By.XPATH, '//div[@class="card-code"]/div[@class="card-code-input"]/input[@id="code"]')
button_enlace = (By.XPATH, '//div[@class="pp-buttons"]/button')
button_cerrar_modal_opcion_de_pago = (By.XPATH, '//div[@class="payment-picker open"]/div[@class="modal"]/div[@class="section active"]/button')
input_message_for_driver = (By.XPATH, '//input[@id="comment"]')
switch_ask_for_a_blanket_and_tissues = (By.XPATH, '//input[@class="switch-input"]')
input_ice_cream = (By.XPATH, '(//div[@class="counter-plus"])[1]')
value_input_ice_cream = (By.XPATH, '(//div[@class="counter-value"])[1]')
button_order_a_taxi_final_part = (By.XPATH, '//div[@class="workflow"]/div[@class="smart-button-wrapper"]/button')
modal_shown_to_search_for_a_taxi = (By.XPATH, '//div[@class="order shown"]')
order_header_title_search_driver = (By.CLASS_NAME, 'order-header-title')